src/main/java/com/epam/tour/entity/Entity.java
package com.epam.tour.entity;

/**
 * The type Entity.
 */
public abstract class Entity {

    /**
     * The Id.
     */
    private int id;

    /**
     * Gets id.
     *
     * @return the id
     */
    public int getId() {
        return id;
    }

    /**
     * Sets id.
     *
     * @param id the id
     */
    public void setId(int id) {
        this.id = id;
    }

}

src/main/java/com/epam/tour/entity/Order.java
package com.epam.tour.entity;

import java.io.Serializable;
import java.util.Date;

/**
 * The type Order.
 */
public class Order extends Entity implements Serializable {


    /**
     * The constant serialVersionUID.
     */
    private static final long serialVersionUID = 2131437530109623077L;
    /**
     * The User.
     */
    private User user;

    /**
     * The Tour.
     */
    private Tour tour;

    /**
     * The Date time.
     */
    private Date dateTime;

    /**
     * The Amount.
     */
    private double amount;

    /**
     * The Paid.
     */
    private boolean paid;

    /**
     * Gets user.
     *
     * @return the user
     */
    public User getUser() {
        return user;
    }

    /**
     * Sets user.
     *
     * @param user the user
     */
    public void setUser(User user) {
        this.user = user;
    }

    /**
     * Gets tour.
     *
     * @return the tour
     */
    public Tour getTour() {
        return tour;
    }

    /**
     * Sets tour.
     *
     * @param tour the tour
     */
    public void setTour(Tour tour) {
        this.tour = tour;
    }

    /**
     * Gets date time.
     *
     * @return the date time
     */
    public Date getDateTime() {
        return (Date) dateTime.clone();
    }

    /**
     * Sets date time.
     *
     * @param dateTime the date time
     */
    public void setDateTime(Date dateTime) {
        this.dateTime = dateTime;
    }

    /**
     * Gets amount.
     *
     * @return the amount
     */
    public double getAmount() {
        return amount;
    }

    /**
     * Sets amount.
     *
     * @param amount the amount
     */
    public void setAmount(double amount) {
        this.amount = amount;
    }

    /**
     * Is paid.
     *
     * @return the boolean
     */
    public boolean isPaid() {
        return paid;
    }

    /**
     * Sets paid.
     *
     * @param paid the paid
     */
    public void setPaid(boolean paid) {
        this.paid = paid;
    }

    /**
     * Equals boolean.
     *
     * @param o the o
     * @return the boolean
     */
    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof Order)) return false;

        Order order = (Order) o;

        if (Double.compare(order.getAmount(), getAmount()) != 0) return false;
        if (isPaid() != order.isPaid()) return false;
        if (getUser() != null ? !getUser().equals(order.getUser()) : order.getUser() != null) return false;
        if (getTour() != null ? !getTour().equals(order.getTour()) : order.getTour() != null) return false;
        return !(getDateTime() != null ? !getDateTime().equals(order.getDateTime()) : order.getDateTime() != null);

    }

    /**
     * Hash code.
     *
     * @return the int
     */
    @Override
    public int hashCode() {
        int result = getUser() != null ? getUser().hashCode() : 0;
        result = 31 * result + (getTour() != null ? getTour().hashCode() : 0);
        result = 31 * result + (getDateTime() != null ? getDateTime().hashCode() : 0);
        long temp = Double.doubleToLongBits(getAmount());
        result = 31 * result + (int) (temp ^ (temp >>> 32));
        result = 31 * result + (isPaid() ? 1 : 0);
        return result;
    }

    /**
     * To string.
     *
     * @return the string
     */
    @Override
    public String toString() {
        final StringBuilder sb = new StringBuilder("Order{");
        sb.append("user=").append(user);
        sb.append(", tour=").append(tour);
        sb.append(", dateTime=").append(dateTime);
        sb.append(", amount=").append(amount);
        sb.append(", paid=").append(paid);
        sb.append('}');
        return sb.toString();
    }
}

src/main/java/com/epam/tour/entity/Role.java
package com.epam.tour.entity;

import java.io.Serializable;

/**
 * The type Role.
 */
public class Role extends Entity implements Serializable{


    /**
     * The constant ROLE_ADMIN.
     */
    public static final String ROLE_ADMIN = "admin";
    /**
     * The constant ROLE_CLIENT.
     */
    public static final String ROLE_CLIENT = "client";
    /**
     * The constant serialVersionUID.
     */
    private static final long serialVersionUID = -6481105593392463256L;

    /**
     * The Rolename.
     */
    private String rolename;


    /**
     * Gets rolename.
     *
     * @return the rolename
     */
    public String getRolename() {
        return rolename;
    }

    /**
     * Sets rolename.
     *
     * @param rolename the rolename
     */
    public void setRolename(String rolename) {
        this.rolename = rolename;
    }

    /**
     * Equals boolean.
     *
     * @param o the o
     * @return the boolean
     */
    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof Role)) return false;

        Role role = (Role) o;

        return !(getRolename() != null ? !getRolename().equals(role.getRolename()) : role.getRolename() != null);

    }

    /**
     * Hash code.
     *
     * @return the int
     */
    @Override
    public int hashCode() {
        return getRolename() != null ? getRolename().hashCode() : 0;
    }

    /**
     * To string.
     *
     * @return the string
     */
    @Override
    public String toString() {
        final StringBuilder sb = new StringBuilder("Role{");
        sb.append("rolename='").append(rolename).append('\'');
        sb.append('}');
        return sb.toString();
    }
}

src/main/java/com/epam/tour/entity/Tour.java
package com.epam.tour.entity;

import java.io.Serializable;

/**
 * The type Tour.
 */
public class Tour extends Entity implements Serializable {


    /**
     * The constant serialVersionUID.
     */
    private static final long serialVersionUID = 3247694199643732647L;
    /**
     * The Tourname.
     */
    private String tourname;

    /**
     * The Details.
     */
    private String details;

    /**
     * The Price.
     */
    private int price;

    /**
     * The Hot.
     */
    private boolean hot;

    /**
     * The Regular discount.
     */
    private int regularDiscount;

    /**
     * The Type.
     */
    private TourType type = TourType.VACATION;

    /**
     * Gets type.
     *
     * @return the type
     */
    public TourType getType() {
        return type;
    }

    /**
     * Sets type.
     *
     * @param type the type
     */
    public void setType(TourType type) {
        this.type = type;
    }

    /**
     * Gets tourname.
     *
     * @return the tourname
     */
    public String getTourname() {
        return tourname;
    }

    /**
     * Sets tourname.
     *
     * @param tourname the tourname
     */
    public void setTourname(String tourname) {
        this.tourname = tourname;
    }

    /**
     * Gets details.
     *
     * @return the details
     */
    public String getDetails() {
        return details;
    }

    /**
     * Sets details.
     *
     * @param details the details
     */
    public void setDetails(String details) {
        this.details = details;
    }

    /**
     * Gets price.
     *
     * @return the price
     */
    public int getPrice() {
        return price;
    }

    /**
     * Sets price.
     *
     * @param price the price
     */
    public void setPrice(int price) {
        this.price = price;
    }

    /**
     * Is hot.
     *
     * @return the boolean
     */
    public boolean isHot() {
        return hot;
    }

    /**
     * Sets hot.
     *
     * @param hot the hot
     */
    public void setHot(boolean hot) {
        this.hot = hot;
    }

    /**
     * Gets regular discount.
     *
     * @return the regular discount
     */
    public int getRegularDiscount() {
        return regularDiscount;
    }

    /**
     * Sets regular discount.
     *
     * @param regularDiscount the regular discount
     */
    public void setRegularDiscount(int regularDiscount) {
        this.regularDiscount = regularDiscount;
    }

    /**
     * Equals boolean.
     *
     * @param o the o
     * @return the boolean
     */
    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof Tour)) return false;

        Tour tour = (Tour) o;

        if (getPrice() != tour.getPrice()) return false;
        if (isHot() != tour.isHot()) return false;
        if (getRegularDiscount() != tour.getRegularDiscount()) return false;
        if (getTourname() != null ? !getTourname().equals(tour.getTourname()) : tour.getTourname() != null)
            return false;
        if (getDetails() != null ? !getDetails().equals(tour.getDetails()) : tour.getDetails() != null) return false;
        return getType() == tour.getType();

    }

    /**
     * Hash code.
     *
     * @return the int
     */
    @Override
    public int hashCode() {
        int result = getTourname() != null ? getTourname().hashCode() : 0;
        result = 31 * result + (getDetails() != null ? getDetails().hashCode() : 0);
        result = 31 * result + getPrice();
        result = 31 * result + (isHot() ? 1 : 0);
        result = 31 * result + getRegularDiscount();
        result = 31 * result + (getType() != null ? getType().hashCode() : 0);
        return result;
    }

    /**
     * To string.
     *
     * @return the string
     */
    @Override
    public String toString() {
        final StringBuilder sb = new StringBuilder("Tour{");
        sb.append("tourname='").append(tourname).append('\'');
        sb.append(", details='").append(details).append('\'');
        sb.append(", price=").append(price);
        sb.append(", hot=").append(hot);
        sb.append(", regularDiscount=").append(regularDiscount);
        sb.append(", type=").append(type);
        sb.append('}');
        return sb.toString();
    }
}

src/main/java/com/epam/tour/entity/TourType.java
package com.epam.tour.entity;

/**
 * The enum Tour type.
 */
public enum TourType {
    /**
     * The VACATION.
     */
    VACATION(1), /**
     * The SHOPPING.
     */
    SHOPPING(2), /**
     * The EXCURSION.
     */
    EXCURSION(3);

    /**
     * The Id.
     */
    private final int id;

    /**
     * Instantiates a new Tour type.
     *
     * @param id the id
     */
    TourType(int id) {
        this.id = id;
    }

    /**
     * Find by id.
     *
     * @param id the id
     * @return the tour type
     */
    public static TourType findById(int id) {
        for (TourType type : TourType.values()) {
            if (type.id == id) {
                return type;
            }
        }

        return null;
    }

    /**
     * Gets id.
     *
     * @return the id
     */
    public int getId() {
        return id;
    }

    /**
     * Gets display name.
     *
     * @return the display name
     */
    public String getDisplayName() {
        return name().toLowerCase();
    }
}

src/main/java/com/epam/tour/entity/User.java
package com.epam.tour.entity;

import java.io.Serializable;

/**
 * The type User.
 */
public class User extends Entity implements Serializable{


    /**
     * The constant serialVersionUID.
     */
    private static final long serialVersionUID = -4139585827910589126L;

    /**
     * The Username.
     */
    private String username;

    /**
     * The Password.
     */
    private String password;

    /**
     * The Role.
     */
    private Role role;

    /**
     * Gets password.
     *
     * @return the password
     */
    public String getPassword() {
        return password;
    }

    /**
     * Sets password.
     *
     * @param password the password
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * Gets username.
     *
     * @return the username
     */
    public String getUsername() {
        return username;
    }

    /**
     * Sets username.
     *
     * @param username the username
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * Gets role.
     *
     * @return the role
     */
    public Role getRole() {
        return role;
    }

    /**
     * Sets role.
     *
     * @param role the role
     */
    public void setRole(Role role) {
        this.role = role;
    }

    /**
     * Equals boolean.
     *
     * @param o the o
     * @return the boolean
     */
    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof User)) return false;

        User user = (User) o;

        if (getUsername() != null ? !getUsername().equals(user.getUsername()) : user.getUsername() != null)
            return false;
        if (getPassword() != null ? !getPassword().equals(user.getPassword()) : user.getPassword() != null)
            return false;
        return !(getRole() != null ? !getRole().equals(user.getRole()) : user.getRole() != null);

    }

    /**
     * Hash code.
     *
     * @return the int
     */
    @Override
    public int hashCode() {
        int result = getUsername() != null ? getUsername().hashCode() : 0;
        result = 31 * result + (getPassword() != null ? getPassword().hashCode() : 0);
        result = 31 * result + (getRole() != null ? getRole().hashCode() : 0);
        return result;
    }

    /**
     * To string.
     *
     * @return the string
     */
    @Override
    public String toString() {
        final StringBuilder sb = new StringBuilder("User{");
        sb.append("username='").append(username).append('\'');
        sb.append(", password='").append(password).append('\'');
        sb.append(", role=").append(role);
        sb.append('}');
        return sb.toString();
    }

}

src/main/java/com/epam/tour/servlet/FrontController.java
package com.epam.tour.servlet;

import com.epam.tour.command.ActionCommand;
import com.epam.tour.helper.RequestHelper;
import com.epam.tour.resource.PathManager;
import org.apache.log4j.Logger;

import javax.servlet.ServletException;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import java.io.IOException;
import java.util.MissingResourceException;

/**
 * The type Front controller.
 */
public class FrontController extends HttpServlet {

    /**
     * The constant LOG.
     */
    private static final Logger LOG = Logger.getRootLogger();
    /**
     * The constant serialVersionUID.
     */
    private static final long serialVersionUID = -4203462103499487575L;
    /**
     * The Error page path.
     */
    private String errorPagePath;

    /**
     * Init void.
     *
     * @throws ServletException the servlet exception
     */
    @Override
    public void init() throws ServletException {
        try {
            errorPagePath = PathManager.INSTANCE.getString("path.error500");
        } catch (MissingResourceException e) {
            LOG.error(e);
        }
    }

    /**
     * Do post.
     *
     * @param request the request
     * @param response the response
     * @throws ServletException the servlet exception
     * @throws IOException the iO exception
     */
    @Override
    protected void doPost(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
        processRequest(request, response);
    }

    /**
     * Do get.
     *
     * @param request the request
     * @param response the response
     * @throws ServletException the servlet exception
     * @throws IOException the iO exception
     */
    @Override
    protected void doGet(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
        processRequest(request, response);
    }

    /**
     * Process request.
     *
     * @param request the request
     * @param response the response
     * @throws ServletException the servlet exception
     * @throws IOException the iO exception
     */
    private void processRequest(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {

        ActionCommand command = RequestHelper.INSTANCE.getCommand(request);

            LOG.info("Command: " + command.getClass().getSimpleName());
            String page = command.execute(request);
            if (page != null) {
                request.getRequestDispatcher(page).forward(request, response);
            } else   {
                request.getRequestDispatcher(errorPagePath).forward(request, response);
            }

        }
    }

src/main/webapp/jsp/login.jsp
<%@ page language="java" pageEncoding="utf8" contentType="text/html;charset=UTF-8" %>
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt" %>
<%@ taglib prefix="auth" uri="http://epam.com/taglib/custom" %>


<fmt:setLocale value="${locale}"/>
<fmt:setBundle basename="message"/>
<c:set var="user" scope="page" value="${auth:user(pageContext.request)}"/>
<html>
<head>
    <title><fmt:message key="auth.page.title"/></title>
    <link rel="stylesheet" href="../css/style.css"/>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
</head>
<body>
<%@include file="../WEB-INF/jspf/header.jspf" %>
<div class="content">
    <h1><fmt:message key="auth.page.title"/></h1>
    <p><fmt:message key="auth.page.message"/></p>
    <form method="post" id="loginForm">
        <input type="hidden" name="command" value="login"/>
        <label for="login"><fmt:message key="auth.page.login_form.login"/> :</label>
        <input id="login" type="text" name="login"/>
        <label for="password"><fmt:message key="auth.page.login_form.password"/>:</label>
        <input id="password" type="password" name="password"/>
        <input type="submit" value="<fmt:message key="auth.page.login_form.submit"/>"/>
    </form>
</div>
<%@include file="../WEB-INF/jspf/footer.jspf" %>
</body>
</html>

src/main/webapp/jsp/main.jsp
<%@ page language="java" pageEncoding="utf8" contentType="text/html;charset=UTF-8" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt" %>
<%@ taglib prefix="auth" uri="http://epam.com/taglib/custom" %>

<fmt:setLocale value="${locale}"/>
<fmt:setBundle basename="message"/>
<c:set var="user" scope="page" value="${auth:user(pageContext.request)}"/>
<html>
<head>
    <title><fmt:message key="main.page.title"/></title>
    <link rel="stylesheet" href="../css/style.css"/>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
</head>
<body>
<%@include file="../WEB-INF/jspf/header.jspf" %>
<div class="content">
    <h1><fmt:message key="main.page.intro.title"/></h1>
    <p><fmt:message key="main.page.intro.body"/></p>
    <h1><fmt:message key="main.page.how_to"/></h1>
    <div class="blocks">
        <div class="block block-search">
            <h1><fmt:message key="block.search.title"/></h1>
            <img src="${pageContext.servletContext.contextPath}/images/search.png"/>
            <p><fmt:message key="block.search.text"/></p>
        </div>
        <div class="block block-order">
            <h1><fmt:message key="block.order.title"/></h1>
            <img src="${pageContext.servletContext.contextPath}/images/order.png"/>
            <p><fmt:message key="block.order.text"/></p>
        </div>
        <div class="block block-complete">
            <h1><fmt:message key="block.complete.title"/></h1>
            <img src="${pageContext.servletContext.contextPath}/images/accept.png"/>
            <p><fmt:message key="block.complete.text"/></p>
        </div>
    </div>
</div>
<%@include file="../WEB-INF/jspf/footer.jspf" %>
</body>
</html>

src/main/webapp/jsp/tours.jsp
<%@ page language="java" pageEncoding="utf8" contentType="text/html;charset=UTF-8" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt" %>
<%@ taglib prefix="auth" uri="http://epam.com/taglib/custom" %>


<fmt:setLocale value="${locale}"/>
<fmt:setBundle basename="message"/>
<c:set var="user" scope="page" value="${auth:user(pageContext.request)}"/>
<html>
<head>
    <title><fmt:message key="tour.title"/></title>
    <link rel="stylesheet" href="../css/style.css"/>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
</head>
<body>
<%@include file="../WEB-INF/jspf/header.jspf" %>
<div class="content" id="tours">
    <c:forEach var="tour" items="${tours}">
        <div class="tour-view">
            <h3>${tour.tourname}</h3>
            <c:set var="type" value="${tour.type.displayName}"/>
            <p class="type type-${type}"><fmt:message key="tour_type.${type}"/><c:if test="${tour.hot}"><span
                    class="hot"><fmt:message key="tour_table.hot"/></span></c:if></p>
            <p class="details">${tour.details}</p>
            <c:set var="discounted" value="${tour.price - (tour.price * tour.regularDiscount * 0.01)}"/>
            <c:choose>
               <c:when test="${regular eq true and discounted < tour.price}">
                    <p class="price"><span class="discounted">${tour.price} USD</span> ${discounted} USD</p>
                </c:when>
                <c:otherwise>
                    <p class="price">${tour.price} USD</p>
                </c:otherwise>
            </c:choose>
            <c:choose>
                <c:when test="${not empty rolename and rolename eq 'client'}">
                    <a class="btn" href="app?c=order&id=${tour.id}&lang=${locale}"><fmt:message key="tour.order"/></a>
                </c:when>
                <c:otherwise>
                    <p class="not-logged"><fmt:message key="tour.not_logged"/></p>
                </c:otherwise>
            </c:choose>
        </div>
    </c:forEach>
</div>
<%@include file="../WEB-INF/jspf/footer.jspf" %>
</body>
</html>